version: "3.9"

services:
  batch:
    build: .
    container_name: batch
    ports:
      - "8082:8080"
    volumes:
      - ./logging/logs:/app/logs
    networks:
      - batch-network

networks:
  batch-network:
    driver: bridge