name: batch
services:
  alloy:
    image: grafana/alloy:latest
    container_name: batch-alloy
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - SERVER_NAME=batch
      - LOKI_ENV=dev
      - LOKI_SERVICE_NAME=batch
    volumes:
      - ./logs:/var/log/app
      - ./alloy.yml:/etc/alloy/alloy.yml
    command: run /etc/alloy/alloy.yml
    restart: unless-stopped

networks:
  default:
    name: budong-network
    external: true